name: Build Image

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - uses: actions/upload-artifact@v3
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
