name: Build Image

on:
  workflow_call:

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - uses: canonical/craft-actions/rockcraft-pack@main
        id: rockcraft

      - uses: actions/upload-artifact@v4
        with:
          name: rock
          path: ${{ steps.rockcraft.outputs.rock }}
