name: Integration tests

on:
  workflow_call:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Install Skopeo
        run: |
          sudo snap install skopeo --edge --devmode

      - uses: actions/download-artifact@v3
        with:
          name: rock

      - name: Import the image to Docker registry
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/gruyaume/${image_name}:${version}"

      - name: Run the image
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          docker run -d -p 3000:3000 --entrypoint /bin/bash ghcr.io/gruyaume/${image_name}:${version} -c 'cd /app && npm run start'

      - name: Check if the app is successfully running
        id: test_image
        run: |
          sleep 10  # Wait for the container to be ready
          curl localhost:3000/ | grep -i 'Mon profil cognitif'
